Fix serial number retrieval and add power
henne49/dbus-opendtu pull request #124
Opened 2023-11-14 09:19 UTC by 0x7878

measurement for Ahoy variant by @
c-graeser 

@c-graeser Please test this again on your hardware

2023-11-14 12:34 UTC, c-graeser requested changes
Zeile 280 muss bündig mit dem darüber liegenden "if..." beginnen:
```
   if self.dtuvariant....
         raise .....
   serial =..... 
```

Zeile 655 kann der Kommentar mit GCG auch entfernt werden

2023-11-20 08:08 UTC, 0x7878 commented
Sorry war berufsbedingt nicht stark eingebunden. Ich denke, jetzt haben wir's 😃

2023-11-20 08:53 UTC, c-graeser approved these changes

2023-11-20 08:58 UTC, henne49 approved these changes

2023-11-20 08:59 UTC, merged