move config.ini to config.example to make upgrades easier.
henne49/dbus-opendtu pull request #163
Opened 2024-04-25 16:28 UTC by stlorenz

I have renamed the example config to `config.example` and updated the doc accordingly. 
With that change, an update does not overwrite the existing `config.ini`

Update .gitignore and README.md files

2024-04-25 18:51 UTC, dsteinkopf commented
I like this!

2024-04-27 07:39 UTC, henne49 commented
@0x7878 we still have the Versioning failing, can you check in the github action

2024-04-27 08:07 UTC, 0x7878 commented
> @0x7878 we still have the Versioning failing, can you check in the github action

> See #164 but either we have to configure a secured way to this or we have to drop this feature.

2024-05-03 08:36 UTC, 0x7878 commented
@stlorenz don't worry. It's just us. We have to improve our GitHub Actions. That's all. We need more time to get it done.

2024-05-27 09:30 UTC, 0x7878 commented
If you push something to this repo, the error should go away and we can merge this.

2024-05-27 19:09 UTC, dsteinkopf commented
Look good to me.

2024-05-27 19:11 UTC, dsteinkopf requested changes

2024-05-27 19:11 UTC, dsteinkopf commented on README.md
> +mv /data/dbus-opendtu/config.example /data/ddbus-opendtu/config.ini
This should be a "cp".

2024-05-28 06:43 UTC, henne49 approved these changes
this looks very good, ready to merge

2024-05-28 07:08 UTC, dsteinkopf approved these changes

2024-05-28 07:27 UTC, merged