Pylint cleanup
henne49/dbus-opendtu pull request #38
Opened 2023-02-21 13:07 UTC by henne49

* cleaned code
* introduced new github actions

2023-03-01 08:28 UTC, dsteinkopf requested changes

2023-03-01 08:28 UTC, dsteinkopf requested changes
.

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
> +                "Deprecated Host ONPREMISE entries must be moved to DEFAULT section")
habe ich zurückgenommen

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
> +            config[f"INVERTER{self.pvinverternumber}"]['Phase'])
ok done

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
>          logging.critical('Error at %s', 'main', exc_info=error)
done

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
done und geändert

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
> +                "Deprecated Host ONPREMISE entries must be moved to DEFAULT section") from error
angepasst

2023-03-04 09:09 UTC, henne49 commented on dbus-opendtu.py
> +        return True
habe ich eingebaut

2023-03-05 10:27 UTC, closed without merging